import Foundation
import CoreGraphics

extension CoreTests {
    static func testSlidePointer() throws {
        let rect = SlidePointerPoint.fittedRect(image: CGSize(width: 200, height: 100), bounds: CGRect(x: 0, y: 0, width: 200, height: 200))
        expect(rect == CGRect(x: 0, y: 50, width: 200, height: 100), "letterbox fitting excludes padding")
        expect(SlidePointerPoint.normalized(CGPoint(x: 100, y: 100), in: rect) == SlidePointerPoint(x: 0.5, y: 0.5), "slide center normalizes")
        expect(SlidePointerPoint.normalized(CGPoint(x: 100, y: 10), in: rect) == nil, "letterbox padding cannot point")
        var touch = SlideTouchIntent()
        let origin = CGPoint(x: 40, y: 80)
        touch.begin(origin, at: 0, rect: rect, touches: 1, enabled: true)
        expect(touch.end(origin, at: 0.2, rect: rect, enabled: true) == .previous, "short left tap navigates")
        touch.begin(CGPoint(x: 160, y: 80), at: 1, rect: rect, touches: 1, enabled: true)
        expect(touch.end(CGPoint(x: 160, y: 80), at: 1.2, rect: rect, enabled: true) == .next, "short right tap navigates")
        touch.begin(origin, at: 2, rect: rect, touches: 1, enabled: true)
        expect(touch.move(CGPoint(x: 60, y: 80), at: 2.1, rect: rect, touches: 1, enabled: true) != nil, "movement points immediately without long press")
        expect(touch.move(CGPoint(x: 70, y: 80), at: 2.11, rect: rect, touches: 1, enabled: true) == nil, "pointer sends bounded to 30Hz")
        expect(touch.move(CGPoint(x: 80, y: 80), at: 2.14, rect: rect, touches: 1, enabled: true) != nil, "next interval sends latest absolute location")
        expect(touch.end(origin, at: 2.2, rect: rect, enabled: true) == nil, "dragging back to start cannot turn page")
        touch.begin(origin, at: 3, rect: rect, touches: 1, enabled: true)
        expect(touch.end(origin, at: 3.6, rect: rect, enabled: true) == nil, "long hold does not navigate")
        touch.begin(origin, at: 4, rect: rect, touches: 1, enabled: true)
        _ = touch.move(origin, at: 4.1, rect: rect, touches: 2, enabled: true)
        expect(touch.end(origin, at: 4.2, rect: rect, enabled: true) == nil, "second finger cancels whole interaction")
        touch.begin(origin, at: 5, rect: rect, touches: 1, enabled: true)
        touch.cancel()
        expect(touch.end(origin, at: 5.2, rect: rect, enabled: true) == nil, "disconnect then reconnect cannot resurrect tap")
        touch.begin(origin, at: 6, rect: rect, touches: 1, enabled: true)
        _ = touch.move(CGPoint(x: 100, y: 10), at: 6.1, rect: rect, touches: 1, enabled: true)
        expect(touch.end(origin, at: 6.2, rect: rect, enabled: true) == nil, "leaving slide permanently cancels tap")
        touch.begin(CGPoint(x: 100, y: 10), at: 7, rect: rect, touches: 1, enabled: true)
        expect(touch.end(origin, at: 7.2, rect: rect, enabled: true) == nil, "starting outside slide cannot navigate")
        var receiver = SlidePointerReceiver()
        let session = UUID()
        let update = SlidePointerUpdate(sessionID: session, sequence: 1, point: SlidePointerPoint(x: 0.4, y: 0.6))
        expect(receiver.accept(update, sessionID: session), "current pointer accepted")
        expect(!receiver.accept(update, sessionID: session), "duplicate pointer rejected")
        expect(receiver.accept(SlidePointerUpdate(sessionID: session, sequence: 3, point: nil), sessionID: session), "clear accepted")
        expect(!receiver.accept(SlidePointerUpdate(sessionID: session, sequence: 2, point: update.point), sessionID: session), "late movement cannot revive cleared pointer")
        expect(!receiver.accept(SlidePointerUpdate(sessionID: UUID(), sequence: 4, point: update.point), sessionID: session), "old connection/session rejected")
        expect(!receiver.accept(SlidePointerUpdate(sessionID: session, sequence: 5, point: SlidePointerPoint(x: 2, y: 0)), sessionID: session), "invalid coordinate rejected")
        let wire = WireMessage(kind: "pointer", pointer: update)
        let encoded = try JSONEncoder().encode(wire)
        expect(WireCodec.decode(encoded)?.pointer?.point == update.point, "pointer wire roundtrip")
        let legacy = try JSONDecoder().decode(PresentationState.self, from: JSONEncoder().encode(PresentationState()))
        expect(legacy.pointerSessionID == nil, "optional pointer contract remains compatible")
    }
}
